targets:
  $default:
    builders:
      markdown_generator:
        enabled: true

builders:
  markdown_generator:
    build_extensions: 
      ".json": ["**.dart"]
    import: "package:i18n/i18n_generator.dart"
    builder_factories: ["i18nGenerator"]
    auto_apply: dependents
    # auto_apply: root_package
    # build_to: cache
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    defaults:
      release_options:
        enabled: true
