targets:
  $default:
    builders:
      markdown_generator:
        enabled: true

builders:
  markdown_generator:
    build_extensions: 
      ".dart": [".md"]
    import: "package:test_docs/markdown_generator.dart"
    # import: "lib/markdown_generator.dart"
    builder_factories: ["markdownGenerator"]
    auto_apply: dependents
    # auto_apply: root_package
    # build_to: cache
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    defaults:
      release_options:
        enabled: true
