name: i18n
description: I18N Generator
version: 0.0.1
homepage: https://github.com/
repository: https://github.com/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  source_gen: ^1.2.2
  build: ^2.3.0
  analyzer:  ^4.1.0
  basic_utils: ^4.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.1.11


flutter:
